fix: bump mce version to 1.2.6 to replace corrupted 1.2.5 PyPI release (#119)
The metrics-computation-engine==1.2.5 package on PyPI has CRC corruption
in two files:
- metrics_computation_engine/processor.py (bad CRC fc166f8c, expected fda30f06)
- metrics_computation_engine/entities/core/data_parser.py (bad CRC 957bddee, expected 01821609)

This causes pip install to fail with:
  zlib.error: Error -3 while decompressing data: invalid distance too far back

Since PyPI doesn't allow replacing existing versions, this bumps to 1.2.6
to provide users with a working release.

Signed-off-by: saphanir <saphanir@cisco.com>